import React,{useState} from 'react';
import {Plus,Pencil,Trash2,Search} from 'lucide-react';
import ModuleScope from '../components/ModuleScope';
import useLocalDrafts from '../hooks/useLocalDrafts';
import './SiteWorkspace.css';
const types={marca:'Marca e identidade',conteudo:'Conteúdo aprovado',tecnico:'Requisitos técnicos',referencia:'Referência visual'};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export default function BaseConhecimentoView({userId,onNavigate}){
 const [items,save,error]=useLocalDrafts('referencias',userId);
 const [query,setQuery]=useState(''),[project,setProject]=useState(''),[active,setActive]=useState(null),[draft,setDraft]=useState(null);
 const projects=[...new Set(items.map(i=>i.project).filter(Boolean))];
 const filtered=items.filter(i=>(!project||i.project===project)&&norm(i.name+' '+i.content+' '+i.project).includes(norm(query)));
 const item=filtered.find(i=>i.id===active)||filtered[0];
 function create(){setDraft({name:'',project:project||'',type:'marca',content:''});}
 function submit(e){e.preventDefault();if(!draft.name.trim()||!draft.content.trim())return;const record={...draft,id:draft.id||crypto.randomUUID(),name:draft.name.trim(),project:draft.project.trim(),updated:new Date().toISOString()};if(save([...items.filter(i=>i.id!==record.id),record])){setActive(record.id);setQuery('');setProject(record.project);setDraft(null);}}
 return <main className="site-workspace"><ModuleScope module="conhecimento" onNavigate={onNavigate}/><p className="workspace-notice">Biblioteca manual por projeto, salva nesta conta e neste navegador. As referências antigas foram preservadas, sem atribuição automática de titularidade. Esta biblioteca ainda não alimenta o gerador automaticamente.</p>
 {error&&<p role="alert">{error}</p>}
 <div className="workspace-row workspace-search"><input aria-label="Buscar referências" placeholder="Buscar por título, conteúdo ou projeto..." value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filtrar projeto" style={{width:'auto',maxWidth:'100%'}} value={project} onChange={e=>setProject(e.target.value)}><option value="">Todos os projetos</option>{projects.map(p=><option key={p}>{p}</option>)}</select><button onClick={create}><Plus size={16}/> Nova referência</button></div>
 <div className="workspace-columns"><aside className="workspace-panel"><h3>{filtered.length} referências</h3>{!filtered.length&&<p className="workspace-empty">Nenhuma referência encontrada. Cadastre a identidade e o conteúdo do seu projeto.</p>}{filtered.map(i=><button key={i.id} className={'workspace-list-item '+(item?.id===i.id?'selected':'')} onClick={()=>{setActive(i.id);setDraft(null);}}><strong>{i.name}</strong><small>{i.project||'Sem projeto'} · {types[i.type]||'Referência'}</small></button>)}</aside>
 <section className="workspace-panel">{draft?<form onSubmit={submit}><h2>{draft.id?'Editar':'Nova'} referência</h2><label>Título<input autoFocus maxLength={150} required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Projeto<input maxLength={120} value={draft.project} onChange={e=>setDraft({...draft,project:e.target.value})}/></label><label>Categoria<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}>{Object.entries(types).map(([id,t])=><option key={id} value={id}>{t}</option>)}</select></label><label>Conteúdo<textarea required maxLength={20000} placeholder="Paleta, tipografia, textos aprovados, páginas e requisitos..." value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})}/></label><div className="workspace-row"><button type="button" onClick={()=>setDraft(null)}>Cancelar</button><button type="submit">Salvar referência</button></div></form>:item?<><header className="workspace-row"><h2>{item.name}</h2><button onClick={()=>setDraft({...item})}><Pencil size={14}/> Editar</button><button aria-label="Excluir referência" onClick={()=>{if(confirm('Excluir esta referência?'))save(items.filter(i=>i.id!==item.id));}}><Trash2 size={14}/></button></header><p className="workspace-empty">{item.project||'Sem projeto'} · {types[item.type]}</p><div className="workspace-reference">{item.content}</div></>:<p className="workspace-empty"><Search size={18}/> Seus textos e referências aparecerão aqui. Não buscamos conteúdos externos nem inventamos respostas.</p>}</section></div></main>;
}
